---
 - name: install haproxy
   package: 
    name: haproxy 
    state: present
   become: yes   

 - name: "copy conf"
   template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
   become: yes

 - name: start haproxy
   service: 
    name: haproxy 
    state: restarted
   become: yes

