---
  - name: "add apt key for node"
    apt_key: 
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
    become: yes
  
  - name: "add node repo"
    apt_repository:
        repo: 'deb https://deb.nodesource.com/{{ nodeversion }} {{ nodeostype }} main' 
    become: yes 

  - name: "Install Node"
    package: 
      name:  "{{ item }}"
      state: present
    with_items:
      - nodejs
      - npm
    become: yes

  - name: "install needed global npm packages"
    npm:
      name: "{{ item }}"
      global: yes
      state: present
    with_items:
      - forever
    become: yes

  - name: "Create symbolic link to node due to known bug"
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      state: link
    become: yes
    